# Generated by Django 5.2.14 on 2026-10-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoraccountrequest',
            name='department',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
