# Generated by Django 5.2.14 on 2026-10-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_doctoraccountrequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoraccountrequest',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='doctoraccountrequest',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctoraccountrequest',
            name='years_experience',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
